[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
script = 'deploy'
broadcast = 'records'
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.23"
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts',
    '@uniswap/v3-core/contracts/=lib/v3-core/contracts',
]
